Name: BOWR BASS
>From: Martin Sant <mfs@edison.GE.COM>

Line  Ring  Noise   +/-  Octv  Note  Fine   Wave  Delay  Rate  Depth   Octv
1+1    OFF   OFF     +    0     00    07     1     11     51     18     0

             Line 1                                 Line 2
             ------                                 ------

         DCO Waveforms                          DCO Waveforms
            4     3                               1      0

         Pitch Envelope                         Pitch Envelope
Rate  00 00 00 00 00 00 00 00          Rate  00 00 00 00 00 00 00 00 
Level 00 00 00 00 00 00 00 00          Level 00 00 00 00 00 00 00 00
      E                                      E

         DCW Keyfollow                          DCW Keyfollow
               7                                      2
 
Rate  74 47 00 00 00 00 00 00          Rate  99 40 00 00 00 00 00 00 
Level 78 00 00 00 00 00 00 00          Level 99 00 00 00 00 00 00 00
         E                                      E

         DCA Keyfollow                          DCA Keyfollow
               2                                      2

Rate  72 38 00 00 00 00 00 00          Rate  72 38 00 00 00 00 00 00
Level 92 00 00 00 00 00 00 00          Level 92 00 00 00 00 00 00 00 
      S  E                                      E


