Name: Synth Bass II
>From: Michael Schaeffer <michaels%tekigm2.tek.com@RELAY.CS.NET>

COMMENT: modified casio
ENVELOPE DATA (wave or key - R1.L1 - R2.L2 - *** - R7.L7 - R8);
DCO1 (wave-env): 2.3-0e
DCW1 (key-env): 7-97.99-43.79-50.74s-52e
DCA1 (key-env): 0-99.99-21e
DETUNE (+- oct - semi - fine): (-)1-0-3
MODULATION (1'or 2' - ring or noise): 1' - ring
VIBRATO (wave-delay-rate-depth): 1-33-55-23
KEYBOARD OCTAVE (+ o -): 0
