Name: Thompson Bass
Similar to the plucked bass sound used on several Thompson Twins records.
After an initial transient, the note fades to a muted drone.

Line 1+2'  Octave -1
Detune -  OCT 0, NOTE 0 FINE 0
Vibrato: Wave 1 Delay 0 Rate 0 Depth 0
Modulation: None

DCO 1 Wave 3 Env 0/0/END
DCW 1 Key 9 Env 99/94 55/23/SUS 37/0/END
DCA 1 Key 0 Env 99/99 63/70/SUS 50/0/END

DCO 2 Wave 3 Env 0/0/END
DCW 2 Key 9 Env 99/94 55/23/SUS 37/0/END
DCA 2 Key 0 Env 99/99 63/70/SUS 50/0/END

