// Auto-generated by scripts/registry_generator.js - DO NOT EDIT MANUALLY
#pragma once

#include <juce_core/juce_core.h>
#include <vector>
#include <string>

namespace CZ101 {
namespace ParameterRegistry {

enum class ParamType { Float, Int, Choice, Bool };

struct ParameterSpec {
    const char* id;
    const char* name;
    const char* category;
    ParamType type;
    float minValue;
    float maxValue;
    float defaultValue;
    float step;
    const char* unit;
    float skew; // Non-symmetric skew factor (1.0 = linear), mirrors juce::NormalisableRange
};

extern const std::vector<ParameterSpec>& getRegistry();
const ParameterSpec* findSpec(const juce::String& paramId);

} // namespace ParameterRegistry
} // namespace CZ101
