export const FACTORY_PRESETS = [
  {
    name: "Init Patch",
    params: {
      "LINE_SELECT": 0,
      "LINE_MIX": 0.5,
      "GLIDE": 0.0,
      "OSC1_WAVEFORM": 0,
      "OSC1_WAVEFORM2": 0,
      "OSC1_LEVEL": 1.0,
      "OSC2_WAVEFORM": 0,
      "OSC2_WAVEFORM2": 0,
      "OSC2_LEVEL": 0.0,
      "DETUNE_COARSE": 0,
      "DETUNE_FINE": 0,
      "DCA_ATTACK": 0.1,
      "DCA_DECAY": 1.0,
      "DCA_SUSTAIN": 1.0,
      "DCA_RELEASE": 0.5,
      "DCW_ATTACK": 0.1,
      "DCW_DECAY": 1.0,
      "DCW_SUSTAIN": 1.0,
      "DCW_RELEASE": 0.5,
      "LFO_WAVE": 0,
      "LFO_RATE": 5.0,
      "LFO_DEPTH": 0.0,
      "LFO_DELAY": 0.0,
      "MOD_VELO_DCW": 0.0,
      "MOD_VELO_DCA": 1.0,
      "MOD_WHEEL_VIB": 0.2,
      "MODERN_LPF_CUTOFF": 20000,
      "MODERN_LPF_RESO": 0.0,
      "CHORUS_MIX": 0.0,
      "DELAY_MIX": 0.0,
      "REVERB_MIX": 0.0,
      "MASTER_VOLUME": 0.8,
      "OPERATION_MODE": 0
    }
  },
  {
    name: "CZ Bass",
    params: {
      "LINE_SELECT": 3, // Line 1+2
      "LINE_MIX": 0.4,
      "GLIDE": 0.0,
      "OSC1_WAVEFORM": 1, // Saw
      "OSC1_LEVEL": 0.6,
      "OSC2_WAVEFORM": 2, // Square
      "OSC2_LEVEL": 0.4,
      "DETUNE_COARSE": 0,
      "DETUNE_FINE": -10, // -10 cents
      "DCA_ATTACK": 0.001,
      "DCA_DECAY": 0.2,
      "DCA_SUSTAIN": 0.5,
      "DCA_RELEASE": 0.15,
      "DCW_ATTACK": 0.01,
      "DCW_DECAY": 0.2,
      "DCW_SUSTAIN": 0.2,
      "DCW_RELEASE": 0.1,
      "LFO_WAVE": 0,
      "LFO_RATE": 0.5,
      "LFO_DEPTH": 0.0,
      "LFO_DELAY": 0.0,
      "MOD_VELO_DCW": 0.0,
      "MOD_VELO_DCA": 1.0,
      "MOD_WHEEL_VIB": 0.0,
      "MODERN_LPF_CUTOFF": 2000,
      "MODERN_LPF_RESO": 0.5,
      "CHORUS_MIX": 0.0,
      "DELAY_MIX": 0.08,
      "REVERB_MIX": 0.08,
      "MASTER_VOLUME": 0.8,
      "OPERATION_MODE": 1 // CZ5000 mode
    }
  },
  {
    name: "Vintage Strings",
    params: {
      "LINE_SELECT": 3,
      "LINE_MIX": 0.5,
      "GLIDE": 0.0,
      "OSC1_WAVEFORM": 1,
      "OSC1_LEVEL": 0.5,
      "OSC2_WAVEFORM": 1,
      "OSC2_LEVEL": 0.5,
      "DETUNE_COARSE": 0,
      "DETUNE_FINE": 5,
      "DCA_ATTACK": 0.4,
      "DCA_DECAY": 0.3,
      "DCA_SUSTAIN": 0.8,
      "DCA_RELEASE": 0.6,
      "DCW_ATTACK": 0.3,
      "DCW_DECAY": 0.4,
      "DCW_SUSTAIN": 0.7,
      "DCW_RELEASE": 0.5,
      "LFO_WAVE": 0,
      "LFO_RATE": 4.5,
      "LFO_DEPTH": 0.0,
      "LFO_DELAY": 0.0,
      "MOD_VELO_DCW": 0.0,
      "MOD_VELO_DCA": 1.0,
      "MOD_WHEEL_VIB": 0.2,
      "MODERN_LPF_CUTOFF": 8000,
      "MODERN_LPF_RESO": 0.3,
      "CHORUS_MIX": 0.15,
      "DELAY_MIX": 0.3,
      "REVERB_MIX": 0.4,
      "MASTER_VOLUME": 0.8,
      "OPERATION_MODE": 1
    }
  },
  {
    name: "Synth Brass",
    params: {
      "LINE_SELECT": 3,
      "LINE_MIX": 0.6,
      "GLIDE": 0.0,
      "OSC1_WAVEFORM": 1,
      "OSC1_LEVEL": 1.0,
      "OSC2_WAVEFORM": 3, // Dbl Sine
      "OSC2_LEVEL": 0.6,
      "DETUNE_COARSE": 0,
      "DETUNE_FINE": 7,
      "DCA_ATTACK": 0.1,
      "DCA_DECAY": 0.2,
      "DCA_SUSTAIN": 0.9,
      "DCA_RELEASE": 0.4,
      "DCW_ATTACK": 0.2,
      "DCW_DECAY": 0.3,
      "DCW_SUSTAIN": 0.8,
      "DCW_RELEASE": 0.4,
      "LFO_WAVE": 0,
      "LFO_RATE": 0.5,
      "LFO_DEPTH": 0.0,
      "LFO_DELAY": 0.0,
      "MOD_VELO_DCW": 0.0,
      "MOD_VELO_DCA": 1.0,
      "MOD_WHEEL_VIB": 0.0,
      "MODERN_LPF_CUTOFF": 5000,
      "MODERN_LPF_RESO": 0.6,
      "CHORUS_MIX": 0.0,
      "DELAY_MIX": 0.0,
      "REVERB_MIX": 0.3,
      "MASTER_VOLUME": 0.8,
      "OPERATION_MODE": 1
    }
  },
  {
    name: "Solo Lead",
    params: {
      "LINE_SELECT": 3,
      "LINE_MIX": 0.5,
      "GLIDE": 0.0,
      "OSC1_WAVEFORM": 2, // Square
      "OSC1_LEVEL": 1.0,
      "OSC2_WAVEFORM": 2,
      "OSC2_LEVEL": 0.6,
      "DETUNE_COARSE": 0,
      "DETUNE_FINE": 0,
      "DCA_ATTACK": 0.001,
      "DCA_DECAY": 0.1,
      "DCA_SUSTAIN": 1.0,
      "DCA_RELEASE": 0.2,
      "DCW_ATTACK": 0.0,
      "DCW_DECAY": 0.0,
      "DCW_SUSTAIN": 1.0,
      "DCW_RELEASE": 0.1,
      "LFO_WAVE": 0,
      "LFO_RATE": 1.0,
      "LFO_DEPTH": 0.1,
      "LFO_DELAY": 0.0,
      "MOD_VELO_DCW": 0.0,
      "MOD_VELO_DCA": 1.0,
      "MOD_WHEEL_VIB": 0.2,
      "MODERN_LPF_CUTOFF": 20000,
      "MODERN_LPF_RESO": 0.0,
      "CHORUS_MIX": 0.0,
      "DELAY_MIX": 0.0,
      "REVERB_MIX": 0.0,
      "MASTER_VOLUME": 0.8,
      "OPERATION_MODE": 2 // Modern Mode
    }
  },
  {
    name: "Modern Key Track",
    params: {
      "LINE_SELECT": 3,
      "LINE_MIX": 0.5,
      "GLIDE": 0.0,
      "OSC1_WAVEFORM": 1, // Saw
      "OSC1_LEVEL": 0.7,
      "OSC2_WAVEFORM": 2, // Square
      "OSC2_LEVEL": 0.4,
      "DETUNE_COARSE": 0,
      "DETUNE_FINE": 5, // +5 cents
      "DCA_ATTACK": 0.001,
      "DCA_DECAY": 0.25,
      "DCA_SUSTAIN": 0.8,
      "DCA_RELEASE": 0.3,
      "DCW_ATTACK": 0.01,
      "DCW_DECAY": 0.4,
      // DCW sustain kept at 0.4 so the authentic key-track curve has room to
      // breathe (at 1.0 it would clamp and the bright/dark shift would be lost).
      "DCW_SUSTAIN": 0.4,
      "DCW_RELEASE": 0.3,
      "LFO_WAVE": 0,
      "LFO_RATE": 5.0,
      "LFO_DEPTH": 0.0,
      "LFO_DELAY": 0.0,
      "MOD_VELO_DCW": 0.0,
      "MOD_VELO_DCA": 1.0,
      "MOD_WHEEL_VIB": 0.2,
      "MODERN_LPF_CUTOFF": 18000,
      "MODERN_LPF_RESO": 0.0,
      "CHORUS_MIX": 0.1,
      "DELAY_MIX": 0.12,
      "REVERB_MIX": 0.15,
      "MASTER_VOLUME": 0.8,
      "OPERATION_MODE": 2, // Modern Mode
      // Free matrix (proprietary format, Modern-only):
      //   Slot 1: Authentic Key Track (11) → DCW (1), depth +1.0 — the exact
      //   hardware Key Follow FIX/VAR curve: dark lows below C3, bright highs.
      "MOD_SLOT_1_SRC": 11,
      "MOD_SLOT_1_DEST": 1,
      "MOD_SLOT_1_DEPTH": 1.0,
      //   Slot 2: Velocity → DCA (2), depth +1.0 — restores the authentic
      //   velocity→amp base that the Modern mode gates off the fixed route.
      "MOD_SLOT_2_SRC": 1,
      "MOD_SLOT_2_DEST": 2,
      "MOD_SLOT_2_DEPTH": 1.0
    }
  }
];
